# Used to speed up the split over time by reusing git's objects
cache_dir: ".gitsplit/ChalkboardEducationV2"

# Path to the repository to split (default = current path)
project_dir: .

# List of splits.
splits:
  - prefix: "back"
    target: "git@github.com:chalkboardedu/ChalkboardEducationV2Back"
  - prefix: "front"
    target: "git@github.com:chalkboardedu/ChalkboardEducationV2Front"

# List of references to split (defined as regexp)
origins:
  - ^master$
  - ^demo$
