# Used to speed up the split over time by reusing git's objects
cache_dir: ".gitsplit/ChalkboardV3Test"

# Path to the repository to split (default = current path)
project_dir: .

# List of splits.
splits:
  - prefix: "back"
    target: "git@github.com:anabeto93/chalkv3BackTest.git"
  - prefix: "front"
    target: "git@github.com:anabeto93/chalkv3FrontTest.git"

# List of references to split (defined as regexp)
origins:
  - ^master$
  - ^demo$
