App\Application\Command\Session\Create:
    properties:
        title:
            - NotBlank: ~
        rank:
            - NotNull: ~
            - Range:
                min: 0
        content:
            - NotNull: ~
            - File:
                mimeTypes: [application/zip]
                mimeTypesMessage: 'validator.session.import.zipFile'
