---

#######
# Dir #
#######

#manala_deploy_dir: /srv/app/chalkboard
manala_deploy_dir: /var/www/html/sites/chalkboard

############
# Releases #
############

manala_deploy_releases: 5

############
# Strategy #
############

manala_deploy_strategy: git

manala_deploy_strategy_git_repo:  "git@github.com:anabeto93/chalkv3BackTest.git"
#manala_deploy_strategy_git_repo:    "git@github.com:chalkboardedu/ChalkboardEducationV2Back.git"
manala_deploy_strategy_git_version: master

##########
# Copied #
##########

# manala_deploy_copied:
#   - vendor

##########
# Shared #
##########

# manala_deploy_shared_files:
#   - app/config/parameters.yml

# manala_deploy_shared_dirs:
#   - var/logs
#   - var/sessions
#   - var/import
#   - web/content

manala_deploy_tasks:
  - make: install@production
  - make: build@production
  #- make: migrate-db@production

manala_deploy_post_tasks:
  #- raw: sudo /bin/systemctl reload php7.1-fpm
  - raw: sudo /bin/systemctl reload php7.2-fpm