---

#######
# Dir #
#######

manala_deploy_dir: /srv/app/chalkboard

############
# Releases #
############

manala_deploy_releases: 5

############
# Strategy #
############

manala_deploy_strategy: git

manala_deploy_strategy_git_repo:    "git@github.com:chalkboardedu/ChalkboardEducationV2Back.git"
manala_deploy_strategy_git_version: master

##########
# Copied #
##########

manala_deploy_copied:
  - vendor

##########
# Shared #
##########

manala_deploy_shared_files:
  - app/config/parameters.yml

manala_deploy_shared_dirs:
  - var/logs
  - var/sessions

manala_deploy_tasks:
  - make: install@production
  - make: build@production

manala_deploy_post_tasks:
  - raw: sudo /bin/systemctl reload php7.1-fpm
