---

#######
# Dir #
#######

manala_deploy_dir: /srv/app/chalkedu

############
# Releases #
############

manala_deploy_releases: 5

############
# Strategy #
############

manala_deploy_strategy: git

manala_deploy_strategy_git_repo:    "git@github.com:chalkboardedu/ChalkboardEducationV2Front.git"
manala_deploy_strategy_git_version: master

##########
# Shared #
##########

manala_deploy_shared_dirs: []

manala_deploy_tasks:
  - make: install@prod
  - make: build@prod