App\Domain\Model\Session:
    session_1:
        __construct:
            - "a6342f0bf7-a2aae-5a485"
            - 1
            - "Découverte de l'api"
            - "This is the content"
            - '@course_1'
            - '@folder_1'
            - false
            - <dateTime()>
            - 771
            - 123123
        updatedAt: <(new DateTime('2017-07-16 04:00:00.000'))>
        contentUpdatedAt: <(new DateTime('2017-07-17 16:00:00.000'))>
    session_2:
        __construct:
            - "a6342f0bf7-a2aae-5a486"
            - 2
            - "Votre première query"
            - "This is the content"
            - '@course_1'
            - '@folder_1'
            - true
            - <dateTime()>
            - 771
            - 123123
        updatedAt: <(new DateTime('2017-07-16 04:00:00.000'))>
        contentUpdatedAt: <(new DateTime('2017-07-17 16:00:00.000'))>
    session_3:
        __construct:
            - "a6342f0bf7-a2aae-5a487"
            - 3
            - "Premier pas avec Redux"
            - "This is the content"
            - '@course_2'
            - null
            - false
            - <dateTime()>
            - 771
            - 123123
        updatedAt: <(new DateTime('2017-07-16 04:00:00.000'))>
        contentUpdatedAt: <(new DateTime('2017-07-17 16:00:00.000'))>
    session_4:
        __construct:
            - "a6342f0bf7-a2aae-5a488"
            - 4
            - "Requêtes et mutations"
            - "This is the content"
            - '@course_1'
            - '@folder_1'
            - true
            - <dateTime()>
            - 771
            - 123123
        updatedAt: <(new DateTime('2017-07-16 04:00:00.000'))>
        contentUpdatedAt: <(new DateTime('2017-07-17 16:00:00.000'))>
    session_5:
        __construct:
            - "a6342f0bf7-a2aae-5a489"
            - 5
            - "Schéma et types"
            - "This is the content"
            - '@course_1'
            - '@folder_1'
            - false
            - <dateTime()>
            - 771
            - 123123
        updatedAt: <(new DateTime('2017-07-16 04:00:00.000'))>
        contentUpdatedAt: <(new DateTime('2017-07-17 16:00:00.000'))>
    session_6:
        __construct:
            - "a6342f0bf7-a2aae-5a50a"
            - 3
            - "Validation"
            - "This is the content"
            - '@course_1'
            - '@folder_1'
            - true
            - <dateTime()>
            - 771
            - 123123
        updatedAt: <(new DateTime('2017-07-16 04:00:00.000'))>
        contentUpdatedAt: <(new DateTime('2017-07-17 16:00:00.000'))>
