App\Domain\Model\User:
    user_dev:
        __construct:
            - "12345-test-98765"
            - "Jean"
            - "Paul"
            - '+33123456789'
            - 'FR'
            - 'fr'
            - 44
            - 'token'
            - <dateTime()>
        apiToken: 'api-key-token-user-1'
        courses:
            - '@course_1'
            - '@course_2'
            - '@course_3'
            - '@course_4'
