App\Application\Command\User\Update:
    properties:
        firstName:
            - NotBlank: ~
        lastName:
            - NotBlank: ~
        phoneNumber:
            - NotBlank: ~
            - Regex:
                pattern: '/^\+/'
                message: 'validator.phoneNumber.mustStartWithPlus'
        country:
            - NotBlank: ~
        locale:
            - NotBlank: ~
