default:
    extensions:
        Behat\Symfony2Extension:
            kernel:
               env: test
        Behat\MinkExtension:
            base_url:  'http://api.chalkboardeducation.dev/app_test.php'
            sessions:
                default:
                    symfony2: ~
    suites:
        default:
            contexts:
                - Features\Behat\Context\CommonContext: ~
