default:
    extensions:
        Behat\Symfony2Extension:
            kernel:
               env: test
        Behat\MinkExtension:
            base_url:  'http://api.chalkboardeducation.dev/app_test.php'
            sessions:
                default:
                    symfony2: ~
        Behatch\Extension: ~
    suites:
        default:
            contexts:
                - Features\Behat\Context\CommonContext: ~
                - Features\Behat\Context\DoctrineORMContext: ~
                - Features\Behat\Context\Domain\CourseContext:
                    - '@Features\Behat\Services\Proxy\CourseProxy'
                - Features\Behat\Context\Domain\SessionContext:
                    - '@Features\Behat\Services\Proxy\SessionProxy'
                - Features\Behat\Context\Domain\FolderContext:
                    - '@Features\Behat\Services\Proxy\FolderProxy'
                - behatch:json
                - behatch:rest
