services:
    App\Ui\Admin\Action\HomeAction:
        autowire: true

    App\Ui\Admin\Action\Course\ListAction:
        autowire: true

    App\Ui\Admin\Action\Course\CreateAction:
        autowire: true

    App\Ui\Admin\Action\User\ListAction:
        autowire: true

    App\Ui\Admin\Action\User\CreateAction:
        autowire: true
