services:
    App\Ui\Admin\Action\HomeAction:
        autowire: true

    App\Ui\Admin\Action\Course\ListAction:
        autowire: true

    App\Ui\Admin\Action\Course\CreateAction:
        autowire: true

    App\Ui\Admin\Action\Course\UpdateAction:
        autowire: true

    App\Ui\Admin\Action\Course\AssignUserAction:
        autowire: true

    App\Ui\Admin\Action\User\ListAction:
        autowire: true

    App\Ui\Admin\Action\User\CreateAction:
        autowire: true

    App\Ui\Admin\Action\User\UpdateAction:
        autowire: true

    App\Ui\Admin\Action\User\ImportAction:
        autowire: true

    App\Ui\Admin\Action\User\ConfirmImportAction:
        autowire: true
        arguments:
            $importDir: '%infrastructure.user_import_dir%'

    App\Ui\Admin\Action\Folder\ListAction:
        autowire: true

    App\Ui\Admin\Action\Folder\DeleteAction:
        autowire: true

    App\Ui\Admin\Action\Folder\CreateAction:
        autowire: true

    App\Ui\Admin\Action\Folder\UpdateAction:
        autowire: true

    App\Ui\Admin\Action\Session\ListAction:
        autowire: true

    App\Ui\Admin\Action\Session\CreateAction:
        autowire: true

    App\Ui\Admin\Action\Session\UpdateAction:
        autowire: true

    App\Ui\Admin\Action\Session\PreviewAction:
        autowire: true

    App\Ui\Admin\Action\Session\DeleteAction:
        autowire: true

    App\Ui\Admin\Action\User\Import\SampleAction:
        autowire: true

    App\Ui\Admin\Action\Session\ProgressionAction:
        autowire: true

    App\Ui\Admin\Action\Session\Quiz\QuestionAction:
        autowire: true

    App\Ui\Admin\Action\Institution\ListAction:
        autowire: true

    App\Ui\Admin\Action\Institution\CreateAction:
        autowire: true

    App\Ui\Admin\Action\Institution\UpdateAction:
        autowire: true

    App\Ui\Admin\Action\Institution\DeleteAction:
        autowire: true

    App\Ui\Admin\Action\Institution\AssignUserAction:
        autowire: true

    App\Ui\Admin\Action\Institution\UserInstitution\ListAction:
        autowire: true

    App\Ui\Admin\Action\UserInstitution\DeleteAction:
        autowire: true

    App\Ui\Admin\Action\Cohort\ListAction:
            autowire: true

    App\Ui\Admin\Action\Cohort\CreateAction:
        autowire: true