services:
    App\Infrastructure\Adapter\QueryBus:
        arguments:
            - '@tactician.commandbus.query'
    App\Application\Adapter\QueryBusInterface: '@App\Infrastructure\Adapter\QueryBus'

    App\Infrastructure\Adapter\CommandBus:
        arguments:
            - '@tactician.commandbus'
    App\Application\Adapter\CommandBusInterface: '@App\Infrastructure\Adapter\CommandBus'

    App\Infrastructure\Adapter\FileStorage:
        autowire: true
    App\Application\Adapter\FileStorageInterface: '@App\Infrastructure\Adapter\FileStorage'


    App\Infrastructure\Adapter\SMSSender:
        autowire: true
        arguments:
            $infoBipUsername: '%infobip_username%'
            $infoBipPassword: '%infobip_password%'
    App\Application\Adapter\SMSSenderInterface: '@App\Infrastructure\Adapter\SMSSender'
