services:
    App\Infrastructure\Adapter\QueryBus:
        arguments:
            - '@tactician.commandbus.query'

    App\Application\Adapter\QueryBusInterface: '@App\Infrastructure\Adapter\QueryBus'

    App\Infrastructure\Adapter\CommandBus:
        arguments:
            - '@tactician.commandbus'

    App\Application\Adapter\CommandBusInterface: '@App\Infrastructure\Adapter\CommandBus'

    App\Infrastructure\Adapter\FileStorage:
        autowire: true

    App\Application\Adapter\FileStorageInterface: '@App\Infrastructure\Adapter\FileStorage'

    App\Infrastructure\Adapter\SMSSender:
        autowire: true
        arguments:
            $infoBipApiKey: '%infobip_api_key%'

    App\Application\Adapter\SMSSenderInterface: '@App\Infrastructure\Adapter\SMSSender'

    App\Infrastructure\Adapter\Translator:
        autowire: true

    App\Application\Adapter\TranslatorInterface: '@App\Infrastructure\Adapter\Translator'

    App\Infrastructure\Adapter\LocaleHelperAdapter:
        autowire: true
    App\Application\Adapter\LocaleHelperInterface: '@App\Infrastructure\Adapter\LocaleHelperAdapter'

    App\Infrastructure\Adapter\SerializerAdapter:
        arguments:
            - '@serializer'
    App\Application\Adapter\SerializerInterface: '@App\Infrastructure\Adapter\SerializerAdapter'
