services:
    #
    # Course
    #
    App\Application\Command\Course\CreateHandler:
        autowire: true
        tags:
            - { name: tactician.handler, command: App\Application\Command\Course\Create }

    App\Application\Command\Course\UpdateHandler:
        autowire: true
        tags:
            - { name: tactician.handler, command: App\Application\Command\Course\Update }

    App\Application\Command\Course\AssignUserHandler:
        autowire: true
        tags:
            - { name: tactician.handler, command: App\Application\Command\Course\AssignUser }

    #
    # User
    #
    App\Application\Command\User\BatchHandler:
        autowire: true
        tags:
            - { name: tactician.handler, command: App\Application\Command\User\Batch }

    App\Application\Command\User\CreateHandler:
        autowire: true
        tags:
            - { name: tactician.handler, command: App\Application\Command\User\Create }

    App\Application\Command\User\UnForceUpdateHandler:
        autowire: true
        tags:
            - { name: tactician.handler, command: App\Application\Command\User\UnForceUpdate }

    App\Application\Command\User\UpdateHandler:
        autowire: true
        tags:
            - { name: tactician.handler, command: App\Application\Command\User\Update }

    App\Application\Command\User\Progression\ValidateSessionHandler:
        autowire: true
        tags:
            - { name: tactician.handler, command: App\Application\Command\User\Progression\ValidateSession }

    App\Application\Command\User\SendLoginAccessHandler:
        autowire: true
        arguments:
            $frontUrl: '%front_url%'
            $frontLoginRoute: '%front_login_route%'
        tags:
            - { name: tactician.handler, command: App\Application\Command\User\SendLoginAccess }

    App\Application\Command\User\ForceUpdateHandler:
        autowire: true
        tags:
            - { name: tactician.handler, command: App\Application\Command\User\ForceUpdate }

    #
    # Folder
    #
    App\Application\Command\Folder\CreateHandler:
        autowire: true
        tags:
            - { name: tactician.handler, command: App\Application\Command\Folder\Create }

    App\Application\Command\Folder\UpdateHandler:
        autowire: true
        tags:
            - { name: tactician.handler, command: App\Application\Command\Folder\Update }

    App\Application\Command\Folder\DeleteHandler:
        autowire: true
        tags:
            - { name: tactician.handler, command: App\Application\Command\Folder\Delete }

    #
    # Session
    #
    App\Application\Command\Session\CreateHandler:
        autowire: true
        tags:
            - { name: tactician.handler, command: App\Application\Command\Session\Create }

    App\Application\Command\Session\DeleteHandler:
        autowire: true
        arguments:
            $uploadDir: '%kernel.root_dir%/../web'
        tags:
            - { name: tactician.handler, command: App\Application\Command\Session\Delete }

    #
    # SMS
    #
    App\Application\Command\SMS\SendHandler:
        autowire: true
        arguments:
            $fromNumber: '%infobip_phone_number%'
        tags:
            - { name: tactician.handler, command: App\Application\Command\SMS\Send }
