services:
    App\Application\Command\Course\CreateHandler:
        autowire: true
        tags:
            - { name: tactician.handler, command: App\Application\Command\Course\Create }

    App\Application\Command\Course\UpdateHandler:
        autowire: true
        tags:
            - { name: tactician.handler, command: App\Application\Command\Course\Update }

    App\Application\Command\User\CreateHandler:
        autowire: true
        tags:
            - { name: tactician.handler, command: App\Application\Command\User\Create }


    App\Application\Command\Folder\CreateHandler:
        autowire: true
        tags:
            - { name: tactician.handler, command: App\Application\Command\Folder\Create }

    App\Application\Command\Session\CreateHandler:
        autowire: true
        tags:
            - { name: tactician.handler, command: App\Application\Command\Session\Create }
