services:
    #
    # Course
    #
    App\Application\Command\Course\CreateHandler:
        autowire: true
        tags:
            - { name: tactician.handler, command: App\Application\Command\Course\Create }

    App\Application\Command\Course\UpdateHandler:
        autowire: true
        tags:
            - { name: tactician.handler, command: App\Application\Command\Course\Update }

    App\Application\Command\Course\AssignUserHandler:
        autowire: true
        tags:
            - { name: tactician.handler, command: App\Application\Command\Course\AssignUser }

    #
    # User
    #
    App\Application\Command\User\BatchHandler:
        autowire: true
        tags:
            - { name: tactician.handler, command: App\Application\Command\User\Batch }

    App\Application\Command\User\CreateHandler:
        autowire: true
        tags:
            - { name: tactician.handler, command: App\Application\Command\User\Create }

    App\Application\Command\User\UnForceUpdateHandler:
        autowire: true
        tags:
            - { name: tactician.handler, command: App\Application\Command\User\UnForceUpdate }

    App\Application\Command\User\UpdateHandler:
        autowire: true
        tags:
            - { name: tactician.handler, command: App\Application\Command\User\Update }

    App\Application\Command\User\Progression\ValidateSessionHandler:
        autowire: true
        tags:
            - { name: tactician.handler, command: App\Application\Command\User\Progression\ValidateSession }

    App\Application\Command\User\Quiz\AnswerSessionQuizHandler:
        autowire: true
        tags:
            - { name: tactician.handler, command: App\Application\Command\User\Quiz\AnswerSessionQuiz }

    App\Application\Command\User\SendLoginAccessHandler:
        autowire: true
        arguments:
            $frontUrl: '%front_url%'
            $frontLoginRoute: '%front_login_route%'
        tags:
            - { name: tactician.handler, command: App\Application\Command\User\SendLoginAccess }

    App\Application\Command\User\ForceUpdateHandler:
        autowire: true
        tags:
            - { name: tactician.handler, command: App\Application\Command\User\ForceUpdate }

    App\Application\Command\User\Import\ImportHandler:
        autowire: true
        arguments:
            $importDir: '%infrastructure.user_import_dir%'
        tags:
            - { name: tactician.handler, command: App\Application\Command\User\Import\Import }

    App\Application\Command\User\Import\ConfirmImportHandler:
        autowire: true
        arguments:
            $importDir: '%infrastructure.user_import_dir%'
        tags:
            - { name: tactician.handler, command: App\Application\Command\User\Import\ConfirmImport }

    #
    # Folder
    #
    App\Application\Command\Folder\CreateHandler:
        autowire: true
        tags:
            - { name: tactician.handler, command: App\Application\Command\Folder\Create }

    App\Application\Command\Folder\UpdateHandler:
        autowire: true
        tags:
            - { name: tactician.handler, command: App\Application\Command\Folder\Update }

    App\Application\Command\Folder\DeleteHandler:
        autowire: true
        tags:
            - { name: tactician.handler, command: App\Application\Command\Folder\Delete }

    #
    # Session
    #
    App\Application\Command\Session\CreateHandler:
        autowire: true
        tags:
            - { name: tactician.handler, command: App\Application\Command\Session\Create }

    App\Application\Command\Session\DeleteHandler:
        autowire: true
        arguments:
            $uploadDir: '%kernel.root_dir%/../web'
        tags:
            - { name: tactician.handler, command: App\Application\Command\Session\Delete }

    App\Application\Command\Session\UpdateHandler:
        autowire: true
        tags:
            - { name: tactician.handler, command: App\Application\Command\Session\Update }

    #
    # SMS
    #
    App\Application\Command\SMS\SendHandler:
        autowire: true
        arguments:
            $fromNumber: '%infobip_phone_number%'
        tags:
            - { name: tactician.handler, command: App\Application\Command\SMS\Send }

    #
    # File
    #
    App\Application\Command\File\RemoveHandler:
        autowire: true
        tags:
            - { name: tactician.handler, command: App\Application\Command\File\Remove }

    #
    # External
    #
    App\Application\Command\External\Infobip\ForwardMessageHandler:
        autowire: true
        arguments:
            $phoneNumberSender: '%infobip_phone_number%'
            $sessionValidationDecodeKey: '%session_validation_private_key_decode%'
            $sessionValidationEncodeKey: '%session_validation_private_key_encode%'
            $frontUrl: '%front_url%'
            $frontValidationSessionUrl: '%front_session_validation_response_route%'
        tags:
            - { name: tactician.handler, command: App\Application\Command\External\Infobip\ForwardMessage }

    #
    # Quiz
    #
    App\Application\Command\Quiz\QuizHandler:
        autowire: true
        tags:
            - { name: tactician.handler, command: App\Application\Command\Quiz\Quiz }

    #
    # Institution
    #
    App\Application\Command\Institution\CreateHandler:
        autowire: true
        tags:
            - { name: tactician.handler, command: App\Application\Command\Institution\Create }

    App\Application\Command\Institution\UpdateHandler:
        autowire: true
        tags:
            - { name: tactician.handler, command: App\Application\Command\Institution\Update }

    App\Application\Command\Institution\DeleteHandler:
        autowire: true
        tags:
            - { name: tactician.handler, command: App\Application\Command\Institution\Delete }

    App\Application\Command\Institution\AssignUserHandler:
        autowire: true
        tags:
            - { name: tactician.handler, command: App\Application\Command\Institution\AssignUser }

    #
    # UserInstitution
    #
    App\Application\Command\UserInstitution\DeleteHandler:
        autowire: true
        tags:
            - { name: tactician.handler, command: App\Application\Command\UserInstitution\Delete }

    #
    # Cohort
    #
    App\Application\Command\Cohort\CreateHandler:
        autowire: true
        tags:
            - { name: tactician.handler, command: App\Application\Command\Cohort\Create }

    App\Application\Command\Cohort\UpdateHandler:
        autowire: true
        tags:
            - { name: tactician.handler, command: App\Application\Command\Cohort\Update }

    App\Application\Command\Cohort\DeleteHandler:
        autowire: true
        tags:
            - { name: tactician.handler, command: App\Application\Command\Cohort\Delete }

    App\Application\Command\Cohort\AssignUserHandler:
        autowire: true
        tags:
            - { name: tactician.handler, command: App\Application\Command\Cohort\AssignUser }

    App\Application\Command\Cohort\AssignCourseHandler:
        autowire: true
        tags:
            - { name: tactician.handler, command: App\Application\Command\Cohort\AssignCourse }

    #
    # CohortUser
    #
    App\Application\Command\CohortUser\DeleteHandler:
        autowire: true
        tags:
            - { name: tactician.handler, command: App\Application\Command\CohortUser\Delete }
