services:
    App\Application\Command\Course\CreateHandler:
        autowire: true
        tags:
            - { name: tactician.handler, command: App\Application\Command\Course\Create }

    App\Application\Command\User\CreateHandler:
        autowire: true
        tags:
            - { name: tactician.handler, command: App\Application\Command\User\Create }
