services:
    App\Ui\Admin\Form\Extension\TranslationDomainExtension:
        tags:
            - { name: 'form.type_extension', extended_type: 'Symfony\Component\Form\Extension\Core\Type\FormType' }

    App\Ui\Admin\Form\Type\Folder\FolderChoiceType:
        autowire: true
        tags:
            - { name: form.type, alias: App\Ui\Admin\Form\Type\Folder\FolderChoiceType }

    App\Ui\Admin\Form\Type\User\UserChoiceType:
        autowire: true
        tags:
            - { name: form.type, alias: App\Ui\Admin\Form\Type\User\UserChoiceType }

    App\Ui\Admin\Form\Type\User\ConfirmImportType:
        autowire: true
        tags:
            - { name: form.type, alias: Symfony\Component\Form\Extension\Core\Type\FormType }

    App\Ui\Admin\Form\Type\Course\CourseChoiceType:
        autowire: true
        tags:
            - { name: form.type, alias: App\Ui\Admin\Form\Type\Course\CourseChoiceType }
