services:
        #
        # Course
        #
        App\Application\Query\Course\CourseListQueryHandler:
            autowire: true
            tags:
                - { name: tactician.handler, command: App\Application\Query\Course\CourseListQuery }
