services:
        #
        # Course
        #
        App\Application\Query\Course\CourseListQueryHandler:
            autowire: true
            tags:
                - { name: tactician.handler, command: App\Application\Query\Course\CourseListQuery }

        #
        # User
        #
        App\Application\Query\User\UserListQueryHandler:
            autowire: true
            tags:
                - { name: tactician.handler, command: App\Application\Query\User\UserListQuery }

        App\Application\Query\User\Import\ImportQueryHandler:
            autowire: true
            arguments:
                $importDir: '%infrastructure.user_import_dir%'
            tags:
                - { name: tactician.handler, command: App\Application\Query\User\Import\ImportQuery }

        #
        # Folder
        #
        App\Application\Query\Folder\FolderListQueryHandler:
            autowire: true
            tags:
                - { name: tactician.handler, command: App\Application\Query\Folder\FolderListQuery }

        #
        # Session
        #
        App\Application\Query\Session\SessionListQueryHandler:
            autowire: true
            tags:
                - { name: tactician.handler, command: App\Application\Query\Session\SessionListQuery }

        App\Application\Query\Session\ProgressionListQueryHandler:
            autowire: true
            tags:
                - { name: tactician.handler, command: App\Application\Query\Session\ProgressionListQuery }

        #
        # Institution
        #
        App\Application\Query\Institution\InstitutionListQueryHandler:
            autowire: true
            tags:
                - { name: tactician.handler, command: App\Application\Query\Institution\InstitutionListQuery }

        App\Application\Query\Institution\UserInstitution\UserInstitutionListQueryHandler:
            autowire: true
            tags:
                - { name: tactician.handler, command: App\Application\Query\Institution\UserInstitution\UserInstitutionListQuery }

        #
        # Cohort
        #
        App\Application\Query\Cohort\CohortListQueryHandler:
            autowire: true
            tags:
                - { name: tactician.handler, command: App\Application\Query\Cohort\CohortListQuery }

        App\Application\Query\Cohort\CohortUser\CohortUserListQueryHandler:
            autowire: true
            tags:
                - { name: tactician.handler, command: App\Application\Query\Cohort\CohortUser\CohortUserListQuery }