services:
    App\Infrastructure\GraphQL\Mutator\ValidateSessionMutator:
        autowire: true
        tags:
            - { name: overblog_graphql.mutation, alias: "validateSessionMutation", method: "mutateValidateSession" }

    App\Infrastructure\GraphQL\Mutator\AnswerSessionQuizMutator:
        autowire: true
        tags:
            - { name: overblog_graphql.mutation, alias: "answerSessionQuiz", method: "handle" }
