services:
    App\Infrastructure\GraphQL\Resolver\UserResolver:
        autowire: true
        tags:
            - { name: overblog_graphql.resolver, alias: "user", method: "resolveUser" }
    App\Infrastructure\GraphQL\Resolver\CourseResolver:
        autowire: true
        tags:
            - { name: overblog_graphql.resolver, alias: "course", method: "resolveCourse" }
            - { name: overblog_graphql.resolver, alias: "courses", method: "resolveCourses" }
    App\Infrastructure\GraphQL\Resolver\HasUpdatesResolver:
        autowire: true
        tags:
            - { name: overblog_graphql.resolver, alias: "hasUpdates", method: "resolveHasUpdates" }
    App\Infrastructure\GraphQL\Resolver\SessionResolver:
        autowire: true
        tags:
            - { name: overblog_graphql.resolver, alias: "session", method: "resolveSession" }
