##########
# Deploy #
##########

deploy:

  vars:
    ansible_ssh_common_args: -o ControlPath=~/.ansible/tmp/%C

  hosts:
    # Staging - Chalkboard
    staging_back_chalkboard:
      ansible_ssh_host: ~
      ansible_ssh_user: ~
      app_env:          staging
    staging_front_chalkboard:
      ansible_ssh_host: ~
      ansible_ssh_user: ~
      app_env:          staging
    # Production - Chalkboard
    production_back_chalkboard:
      #ansible_ssh_host: ec2-52-56-98-247.eu-west-2.compute.amazonaws.com
      ansible_ssh_host: appserver
      #ansible_ssh_user: app
      ansible_ssh_user: ansadm
      app_env:          production
    production_front_chalkboard:
      #ansible_ssh_host: ec2-52-56-98-247.eu-west-2.compute.amazonaws.com
      ansible_ssh_host: appserver
      #ansible_ssh_user: app
      ansible_ssh_user: ansadm
      app_env:          production

  children:
    # Staging
    deploy_staging_back_chalkboard:
      hosts:
        staging_back_chalkboard:
      vars:
        app: chalkboard
    deploy_staging_front_chalkboard:
      hosts:
        staging_front_chalkboard:
      vars:
        app: chalkedu
    # Production
    deploy_production_back_chalkboard:
      hosts:
        production_back_chalkboard:
      vars:
        app: chalkboard
    deploy_production_front_chalkboard:
      hosts:
        production_front_chalkboard:
      vars:
        app: chalkedu
