App\Domain\Model\CohortUser:
    type: entity
    table: cohort_user
    id:
        cohort:
            associationKey: true
        user:
            associationKey: true
    fields:
        assignedAt:
            type: datetime
    manyToOne:
        cohort:
            targetEntity: App\Domain\Model\Cohort
            inversedBy: cohortUsers
            joinColumn:
                onDelete: CASCADE
                nullable: false
        user:
            targetEntity: App\Domain\Model\User
            inversedBy: cohortUsers
            joinColumn:
                onDelete: CASCADE
                nullable: false