App\Domain\Model\Course:
    type: entity
    table: course
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        uuid:
            type: string
            unique: true
        title:
            type: string
        description:
            type: text
            nullable: true
        teacherName:
            type: string
        createdAt:
            type: datetime
        updatedAt:
            type: datetime
    oneToMany:
        folders:
            targetEntity: App\Domain\Model\Folder
            mappedBy: course
        sessions:
            targetEntity: App\Domain\Model\Session
            mappedBy: course
