App\Domain\Model\Folder:
    type: entity
    table: folder
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        uuid:
            type: string
            unique: true
        title:
            type: string
        createdAt:
            type: datetime
        updatedAt:
            type: datetime
        size:
            type: integer
    manyToOne:
        course:
            targetEntity: App\Domain\Model\Course
            inversedBy: folders
            joinColumn:
                onDelete: CASCADE
                nullable: false
