App\Domain\Model\Institution:
    type: entity
    table: institution
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        uuid:
            type: string
            unique: true
        name:
            type: string
            unique: true
        createdAt:
            type: datetime
        updatedAt:
            type: datetime
        size:
            type: integer
    oneToMany:
        cohorts:
            targetEntity: App\Domain\Model\Cohort
            mappedBy: institution
        courses:
            targetEntity: App\Domain\Model\Course
            mappedBy: institution
