App\Domain\Model\Session\Answer:
    type: entity
    table: session_answer
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        title:
            type: text
        correct:
            type: boolean
        createdAt:
            type: datetime
        updatedAt:
            type: datetime
    manyToOne:
        question:
            targetEntity: App\Domain\Model\Session\Question
            inversedBy: answers
            joinColumn:
                onDelete: CASCADE
                nullable: false
