App\Domain\Model\Upload\File:
    type: entity
    table: upload_file
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        path:
            type: string
        createdAt:
            type: datetime
