App\Domain\Model\UserInstitution:
    type: entity
    table: user_institution
    id:
        user:
            associationKey: true
        institution:
            associationKey: true
    fields:
        assignedAt:
            type: datetime
    manyToOne:
        user:
            targetEntity: App\Domain\Model\User
            inversedBy: userInstitutions
            joinColumn:
                onDelete: CASCADE
                nullable: false
        institution:
            targetEntity: App\Domain\Model\Institution
            inversedBy: userInstitutions
            joinColumn:
                onDelete: CASCADE
                nullable: false
