App\Domain\Model\User:
    type: entity
    table: user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        uuid:
            type: string
            unique: true
        firstName:
            type: string
        lastName:
            type: string
        phoneNumber:
            type: string
            unique: true
        country:
            type: string
        locale:
            type: string
            option:
              default: 'en'
        size:
            type: integer
        createdAt:
            type: datetime
        updatedAt:
            type: datetime
        lastLoginAccessNotificationAt:
            type: datetime
            nullable: true
        apiToken:
            type: string
        forceUpdate:
            type: boolean
    oneToMany:
        userCourses:
            targetEntity: App\Domain\Model\UserCourse
            mappedBy: user
