_admin_routes:
    resource: 'routing/admin.yml'
    prefix: /admin

_api_routes:
    resource: 'routing/api.yml'
    prefix: /api

_external_route:
    resource: 'routing/external.yml'
    prefix: /external
