_admin_routes:
    resource: 'routing/admin.yml'
    prefix: /admin

_api_routes:
    resource: 'routing/api.yml'
    prefix: /api

overblog_graphql_graphiql:
    resource: "@OverblogGraphQLBundle/Resources/config/routing/graphiql.yml"
