# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        api_key_user_provider:
            id: App\Infrastructure\Security\Api\ApiKeyUserProvider

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~

        graphql:
            pattern: ^/api/graphql
            stateless: true
            provider: api_key_user_provider
            simple_preauth:
                authenticator: App\Infrastructure\Security\Api\ApiKeyAuthenticator
