security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
    providers:
        in_memory:
            memory:
                users:
                    admin: { password: "%admin_password%", roles: 'ROLE_ADMIN' }
        api_key_user_provider:
            id: App\Infrastructure\Security\Api\ApiKeyUserProvider

    firewalls:
        graphql:
            pattern: ^/api/graphql
            stateless: true
            provider: api_key_user_provider
            simple_preauth:
                authenticator: App\Infrastructure\Security\Api\ApiKeyAuthenticator

        main:
            pattern: "^/admin"
            anonymous: true
            http_basic: ~

    access_control:
        - { path: "^/admin", role: ['ROLE_ADMIN'] }
