security:
    providers:
        api_key_user_provider:
            id: App\Infrastructure\Security\Api\ApiKeyUserProvider

    firewalls:
        graphql:
            pattern: ^/api/graphql
            stateless: true
            provider: api_key_user_provider
            simple_preauth:
                authenticator: App\Infrastructure\Security\Api\ApiKeyAuthenticator

        main:
            anonymous: true
