services:
    #
    # Storage
    #
    Features\Behat\Services\Storage\Storage:
        autowire: true
    # Storage Interface
    Features\Behat\Domain\Storage\StorageInterface: '@Features\Behat\Services\Storage\Storage'

    #
    # Manager
    #
    Features\Behat\Services\Manager\CourseManager:
        autowire: true

    Features\Behat\Services\Manager\FolderManager:
        autowire: true

    Features\Behat\Services\Manager\SessionManager:
        autowire: true

    Features\Behat\Services\Manager\UserManager:
        autowire: true

    Features\Behat\Services\Manager\QuestionManager:
        autowire: true

    Features\Behat\Services\Manager\AnswerManager:
        autowire: true

    Features\Behat\Services\Manager\SessionQuizResultManager:
        autowire: true

    #
    # Proxy
    #
    Features\Behat\Services\Proxy\CourseProxy:
        autowire: true
    Features\Behat\Domain\Proxy\CourseProxyInterface: '@Features\Behat\Services\Proxy\CourseProxy'

    Features\Behat\Services\Proxy\SessionProxy:
        autowire: true
    Features\Behat\Domain\Proxy\SessionProxyInterface: '@Features\Behat\Services\Proxy\SessionProxy'

    Features\Behat\Services\Proxy\FolderProxy:
        autowire: true
    Features\Behat\Domain\Proxy\FolderProxyInterface: '@Features\Behat\Services\Proxy\FolderProxy'

    Features\Behat\Services\Proxy\UserProxy:
        autowire: true
    Features\Behat\Domain\Proxy\UserProxyInterface: '@Features\Behat\Services\Proxy\FolderProxy'

    Features\Behat\Services\Proxy\AnswerProxy:
        autowire: true
    Features\Behat\Domain\Proxy\AnswerProxyInterface: '@Features\Behat\Services\Proxy\AnswerProxy'

    Features\Behat\Services\Proxy\QuestionProxy:
        autowire: true
    Features\Behat\Domain\Proxy\QuestionProxyInterface: '@Features\Behat\Services\Proxy\QuestionProxy'

    Features\Behat\Services\Proxy\SessionQuizResultProxy:
        autowire: true
    Features\Behat\Domain\Proxy\SessionQuizResultProxyInterface: '@Features\Behat\Services\Proxy\SessionQuizResultProxy'
