# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    admin_action_home:
        class: ChalkBoardEducation\Ui\Bundle\AdminBundle\Action\Home
        autowire: true
