Course:
    type: object
    config:
        description: "A course"
        fields:
            uuid:
                type: "String!"
                description: "The uuid of the course."
            title:
                type: "String!"
                description: "The title of the course."
            description:
                type: "String"
                description: "The description of the course."
            teacherName:
                type: "String!"
                description: "The name of the teacher of the course."
            createdAt:
                type: "DateTime!"
                description: "The creation date of the course in format 2017-01-15 10:00:00.000"
            folders:
                type: "[Folder]"

