Mutation:
    type: object
    config:
        fields:
            validateSessionMutation:
                type: "Boolean"
                resolve: "@=mutation('validateSessionMutation', [args['uuid']])"
                args:
                    uuid:
                        type: "String!"
