Query:
    type: object
    config:
        description: "Chalkboard Education API"
        fields:
            user:
                type: "User!"
                resolve: "@=resolver('user')"
            courses:
                type: "[Course]"
                resolve: "@=resolver('courses')"
            hasUpdates:
                type: "HasUpdates"
                args:
                    dateLastUpdate:
                        type: "DateTime"
                resolve: "@=resolver('hasUpdates', [args])"
            session:
                type: "Session"
                args:
                    uuid:
                        description: "The uuid of the session"
                        type: "String!"
                resolve: "@=resolver('session', [args])"
            currentDate:
                type: "DateTime"
                resolve: "@=resolver('currentDate')"
