Query:
    type: object
    config:
        description: "Chalkboard Education API"
        fields:
            course:
                type: "Course"
                args:
                    uuid:
                        description: "The uuid of the course"
                        type: "String!"
                resolve: "@=resolver('course', [args])"
            courses:
                type: "[Course]"
                args:
                    offset:
                        type: "Int"
                        defaultValue: 0
                    limit:
                        type: "Int"
                        defaultValue: 10
                resolve: "@=resolver('courses', [args])"
