Query:
    type: object
    config:
        description: "Chalkboard Education API"
        fields:
            course:
                type: "Course"
                args:
                    uuid:
                        description: "The uuid of the course"
                        type: "String!"
                resolve: "@=resolver('course', [args])"
            courses:
                type: "[Course]"
                resolve: "@=resolver('courses')"
            hasUpdates:
                type: "HasUpdates"
                args:
                    dateLastUpdate:
                        type: "DateTime"
                resolve: "@=resolver('hasUpdates', [args])"

