Session:
    type: object
    config:
        description: "Session"
        fields:
            uuid:
                type: "String!"
                description: "uuid"
            title:
                type: "String!"
                description: "Title of the session"
            validated:
                type: "Boolean!"
                description: "Is the session validated by the user"
            needValidation:
                type: "Boolean!"
                description: "Does the session required to send a validation at the end"
            content:
                type: "String"
                description: "Html content of the session"
            updatedAt:
                type: "DateTime!"
                description: "Last update of the session in format 2017-01-15 10:00"
            contentUpdatedAt:
                type: "DateTime!"
                description: "Last update of the session content in format 2017-01-15 10:00"
            files:
                type: "[SessionFile]"
                description: "Images of the session"
            questions:
                type: "[Question]"
                description: "Question of the quiz"
