Session:
    type: object
    config:
        description: "Session"
        fields:
            uuid:
                type: "String!"
                description: "uuid"
            title:
                type: "String!"
                description: "Title of the session"
            content:
                type: "String"
                description: "Html content of the session"
            updatedAt:
                type: "DateTime!"
                description: "Last update of the session"
