User:
    type: object
    config:
        description: "User"
        fields:
            uuid:
                type: "String!"
                description: "uuid"
            firstName:
                type: "String!"
            lastName:
                type: "String!"
            country:
                type: "String!"
            countryCode:
                type: "String!"
                description: "ISO 3166-1 alpha-2 country code"
            phoneNumber:
                type: "String!"
            locale:
                type: "String!"
