overblog_graphql:
    definitions:
        schema:
            query: Query
            mutation: ~
        mappings:
            types:
                -
                    type: yml
                    dir: "%kernel.project_dir%/app/config/graphql"
    templates:
        graphiql: '::graphiql.html.twig'
