services:
    App\Infrastructure\Normalizer\FolderNormalizer:
        autowire: true

    App\Infrastructure\Normalizer\SessionNormalizer:
        autowire: true

    App\Infrastructure\Normalizer\CourseNormalizer:
        autowire: true

    App\Infrastructure\Normalizer\Session\FileNormalizer:
        autowire: true

    App\Infrastructure\Normalizer\UserNormalizer:
        autowire: true

    App\Infrastructure\Normalizer\Session\QuestionNormalizer:
        autowire: true

    App\Infrastructure\Normalizer\Session\AnswerNormalizer:
        autowire: true
