services:
    App\Infrastructure\Normalizer\FolderNormalizer:
        arguments:
            - '@datetime'
    App\Infrastructure\Normalizer\SessionNormalizer:
        autowire: true
    App\Infrastructure\Normalizer\CourseNormalizer:
        autowire: true

    App\Infrastructure\Normalizer\Session\FileNormalizer:
        autowire: true
