services:
    App\Infrastructure\Repository\Paginator:
        autowire: true

    App\Infrastructure\Repository\CourseRepository:
        autowire: true
    App\Domain\Repository\CourseRepositoryInterface: '@App\Infrastructure\Repository\CourseRepository'

    App\Infrastructure\Repository\SessionRepository:
        autowire: true
    App\Domain\Repository\SessionRepositoryInterface: '@App\Infrastructure\Repository\SessionRepository'

    App\Infrastructure\Repository\FolderRepository:
        autowire: true
    App\Domain\Repository\FolderRepositoryInterface: '@App\Infrastructure\Repository\FolderRepository'

    App\Infrastructure\Repository\UserRepository:
        autowire: true
    App\Domain\Repository\UserRepositoryInterface: '@App\Infrastructure\Repository\UserRepository'

    App\Infrastructure\Repository\Session\FileRepository:
        autowire: true
    App\Domain\Repository\Session\FileRepositoryInterface: '@App\Infrastructure\Repository\Session\FileRepository'

    App\Infrastructure\Repository\User\ProgressionRepository:
        autowire: true
    App\Domain\Repository\User\ProgressionRepositoryInterface: '@App\Infrastructure\Repository\User\ProgressionRepository'

    App\Infrastructure\Repository\Upload\FileRepository:
        autowire: true
    App\Domain\Repository\Upload\FileRepositoryInterface: '@App\Infrastructure\Repository\Upload\FileRepository'

    App\Infrastructure\Repository\UserCourseRepository:
        autowire: true
    App\Domain\Repository\UserCourseRepositoryInterface: '@App\Infrastructure\Repository\UserCourseRepository'

    App\Infrastructure\Repository\Session\AnswerRepository:
        autowire: true
    App\Domain\Repository\Session\AnswerRepositoryInterface: '@App\Infrastructure\Repository\Session\AnswerRepository'

    App\Infrastructure\Repository\Session\QuestionRepository:
        autowire: true
    App\Domain\Repository\Session\QuestionRepositoryInterface: '@App\Infrastructure\Repository\Session\QuestionRepository'
