admin_home:
    path: /
    methods: [GET]
    defaults: { _controller: App\Ui\Admin\Action\HomeAction }

#
# Course
#
admin_course_list:
    path: /course
    methods: [GET]
    defaults: { _controller: App\Ui\Admin\Action\Course\ListAction }

admin_course_create:
    path: /course/create
    methods: [GET, POST]
    defaults: { _controller: App\Ui\Admin\Action\Course\CreateAction }

admin_course_update:
    path: /course/update/{course}
    methods: [GET, POST]
    requirements:
        course: \d+
    defaults: { _controller: App\Ui\Admin\Action\Course\UpdateAction }

admin_course_assign_user:
    path: /course/{course}/student
    methods: [GET, POST]
    requirements:
        course: \d+
    defaults: { _controller: App\Ui\Admin\Action\Course\AssignUserAction }

#
# User
#
admin_user_list:
    path: /user
    methods: [GET, POST]
    defaults: { _controller: App\Ui\Admin\Action\User\ListAction }

admin_user_create:
    path: /user/create
    methods: [GET, POST]
    defaults: { _controller: App\Ui\Admin\Action\User\CreateAction }

admin_user_update:
    path: /user/{user}/update
    methods: [GET, POST]
    requirements:
        user: \d+
    defaults: { _controller: App\Ui\Admin\Action\User\UpdateAction }

admin_user_import:
    path: /user/import
    methods: [GET, POST]
    defaults: { _controller: App\Ui\Admin\Action\User\ImportAction }

admin_user_import_confirm:
    path: /user/import/{file}/confirm
    methods: [GET, POST]
    defaults: { _controller: App\Ui\Admin\Action\User\ConfirmImportAction }

admin_user_import_sample:
    path: /user/import/sample
    methods: [GET]
    defaults: { _controller: App\Ui\Admin\Action\User\Import\SampleAction }

#
# Folder
#
admin_folder_list:
    path: /course/{course}/folder
    methods: [GET]
    requirements:
        course: \d+
    defaults: { _controller: App\Ui\Admin\Action\Folder\ListAction }

admin_folder_create:
    path: /course/{course}/folder/create
    methods: [GET, POST]
    requirements:
        course: \d+
    defaults: { _controller: App\Ui\Admin\Action\Folder\CreateAction }

admin_folder_update:
    path: /course/{course}/folder/update/{folder}
    methods: [GET, POST]
    requirements:
        course: \d+
        folder: \d+
    defaults: { _controller: App\Ui\Admin\Action\Folder\UpdateAction }

admin_folder_delete:
    path: /course/{course}/folder/delete/{folder}
    methods: [DELETE]
    requirements:
        course: \d+
        folder: \d+
    defaults: { _controller: App\Ui\Admin\Action\Folder\DeleteAction }

#
# Session
#
admin_session_list:
    path: /course/{course}/session
    methods: [GET]
    requirements:
        course: \d+
    defaults: { _controller: App\Ui\Admin\Action\Session\ListAction }

admin_session_create:
    path: /course/{course}/session/create
    methods: [GET, POST]
    requirements:
        course: \d+
    defaults: { _controller: App\Ui\Admin\Action\Session\CreateAction }

admin_session_update:
    path: /course/{course}/session/{session}/update
    methods: [GET, POST]
    requirements:
        course: \d+
        session: \d+
    defaults: { _controller: App\Ui\Admin\Action\Session\UpdateAction }

admin_session_preview:
    path: /course/{course}/session/{session}/preview
    methods: [GET]
    requirements:
        course: \d+
        session: \d+
    defaults: { _controller: App\Ui\Admin\Action\Session\PreviewAction }

admin_session_delete:
    path: /course/{course}/session/{session}/delete
    methods: [DELETE]
    requirements:
        course: \d+
        session: \d+
    defaults: { _controller: App\Ui\Admin\Action\Session\DeleteAction }

admin_session_progression:
    path: /course/{course}/session/{session}/progression
    methods: [GET]
    requirements:
        course: \d+
        session: \d+
    defaults: { _controller: App\Ui\Admin\Action\Session\ProgressionAction }

#
# Quiz
#
admin_session_quiz:
    path: /course/{course}/session/{session}/quiz
    methods: [GET, POST]
    requirements:
        course: \d+
        session: \d+
    defaults: { _controller: App\Ui\Admin\Action\Session\Quiz\QuestionAction }

#
# Institution
#
admin_institution_list:
    path: /institutions
    methods: [GET]
    defaults: { _controller: App\Ui\Admin\Action\Institution\ListAction }

admin_institution_create:
    path: /institutions/create
    methods: [GET, POST]
    defaults: { _controller: App\Ui\Admin\Action\Institution\CreateAction }

admin_institution_update:
    path: /institutions/update/{institution}
    methods: [GET, POST]
    requirements:
        institution: \d+
    defaults: { _controller: App\Ui\Admin\Action\Institution\UpdateAction }

admin_institution_delete:
    path: /institutions/delete/{institution}
    methods: [DELETE]
    requirements:
        institution: \d+
    defaults: { _controller: App\Ui\Admin\Action\Institution\DeleteAction }

admin_institution_assign_users:
    path: /institutions/{institution}/users/assign
    methods: [GET, POST]
    requirements:
        institution: \d+
    defaults: { _controller: App\Ui\Admin\Action\Institution\AssignUserAction }

admin_institution_user_list:
    path: /institutions/{institution}/users
    methods: [GET, POST]
    requirements:
        institution: \d+
    defaults: { _controller: App\Ui\Admin\Action\Institution\UserInstitution\ListAction }

#
# UserInstitution
#
admin_user_institution_delete:
    path: /institutions/{institution}/users/{user}/delete
    methods: [GET]
    requirements:
        institution: \d+
        user: \d+
    defaults: { _controller: App\Ui\Admin\Action\UserInstitution\DeleteAction }

#
# Cohort
#
admin_cohort_list:
    path: /institutions/{institution}/cohorts
    methods: [GET]
    requirements:
        institution: \d+
    defaults: { _controller: App\Ui\Admin\Action\Cohort\ListAction }

admin_cohort_create:
    path: /instistutions/{institution}/cohorts/create
    methods: [GET, POST]
    requirements:
        institution: \d+
    defaults: { _controller: App\Ui\Admin\Action\Cohort\CreateAction }

admin_cohort_update:
    path: /institutions/{institution}/cohorts/update/{cohort}
    methods: [GET, POST]
    requirements:
        institution: \d+
        cohort: \d+
    defaults: { _controller: App\Ui\Admin\Action\Cohort\UpdateAction }

admin_cohort_delete:
    path: /institutions/{institution}/cohorts/delete/{cohort}
    methods: [DELETE]
    requirements:
        institution: \d+
        cohort: \d+
    defaults: { _controller: App\Ui\Admin\Action\Cohort\DeleteAction }

admin_cohort_user_list:
    path: /institutions/{institution}/cohorts/{cohort}/users
    methods: [GET, POST]
    requirements:
        institution: \d+
        cohort: \d+
    defaults: { _controller: App\Ui\Admin\Action\Cohort\CohortUser\ListAction }

admin_cohort_assign_users:
    path: /institutions/{institution}/cohorts/{cohort}/users/assign
    methods: [GET, POST]
    requirements:
        institution: \d+
        cohort: \d+
    defaults: { _controller: App\Ui\Admin\Action\Cohort\AssignUserAction }

#
# CohortUser
#
admin_cohort_user_delete:
    path: /institutions/{institution}/cohorts/{cohort}/users/delete/{user}
    methods: [GET]
    requirements:
        institution: \d+
        cohort: \d+
        user: \d+
    defaults: { _controller: App\Ui\Admin\Action\CohortUser\DeleteAction }