admin_home:
    path: /
    methods: [GET]
    defaults: { _controller: App\Ui\Admin\Action\HomeAction }

#
# Course
#
admin_course_list:
    path: /course
    methods: [GET]
    defaults: { _controller: App\Ui\Admin\Action\Course\ListAction }

admin_course_create:
    path: /course/create
    methods: [GET, POST]
    defaults: { _controller: App\Ui\Admin\Action\Course\CreateAction }

admin_course_update:
    path: /course/update/{course}
    methods: [GET, POST]
    requirements:
        course: \d+
    defaults: { _controller: App\Ui\Admin\Action\Course\UpdateAction }

admin_course_assign_user:
    path: /course/{course}/student
    methods: [GET, POST]
    requirements:
        course: \d+
    defaults: { _controller: App\Ui\Admin\Action\Course\AssignUserAction }

#
# User
#
admin_user_list:
    path: /user
    methods: [GET, POST]
    defaults: { _controller: App\Ui\Admin\Action\User\ListAction }

admin_user_create:
    path: /user/create
    methods: [GET, POST]
    defaults: { _controller: App\Ui\Admin\Action\User\CreateAction }

admin_user_update:
    path: /user/{user}/update
    methods: [GET, POST]
    requirements:
        user: \d+
    defaults: { _controller: App\Ui\Admin\Action\User\UpdateAction }

admin_user_import:
    path: /user/import
    methods: [GET, POST]
    defaults: { _controller: App\Ui\Admin\Action\User\ImportAction }

admin_user_import_confirm:
    path: /user/import/{file}/confirm
    methods: [GET, POST]
    defaults: { _controller: App\Ui\Admin\Action\User\ConfirmImportAction }

admin_user_import_sample:
    path: /user/import/sample
    methods: [GET]
    defaults: { _controller: App\Ui\Admin\Action\User\Import\SampleAction }

#
# Folder
#
admin_folder_list:
    path: /course/{course}/folder
    methods: [GET]
    requirements:
        course: \d+
    defaults: { _controller: App\Ui\Admin\Action\Folder\ListAction }

admin_folder_create:
    path: /course/{course}/folder/create
    methods: [GET, POST]
    requirements:
        course: \d+
    defaults: { _controller: App\Ui\Admin\Action\Folder\CreateAction }

admin_folder_update:
    path: /course/{course}/folder/update/{folder}
    methods: [GET, POST]
    requirements:
        course: \d+
        folder: \d+
    defaults: { _controller: App\Ui\Admin\Action\Folder\UpdateAction }

admin_folder_delete:
    path: /course/{course}/folder/delete/{folder}
    methods: [DELETE]
    requirements:
        course: \d+
        folder: \d+
    defaults: { _controller: App\Ui\Admin\Action\Folder\DeleteAction }

#
# Session
#
admin_session_list:
    path: /course/{course}/session
    methods: [GET]
    requirements:
        course: \d+
    defaults: { _controller: App\Ui\Admin\Action\Session\ListAction }

admin_session_create:
    path: /course/{course}/session/create
    methods: [GET, POST]
    requirements:
        course: \d+
    defaults: { _controller: App\Ui\Admin\Action\Session\CreateAction }

admin_session_update:
    path: /course/{course}/session/{session}/update
    methods: [GET, POST]
    requirements:
        course: \d+
        session: \d+
    defaults: { _controller: App\Ui\Admin\Action\Session\UpdateAction }

admin_session_preview:
    path: /course/{course}/session/{session}/preview
    methods: [GET]
    requirements:
        course: \d+
        session: \d+
    defaults: { _controller: App\Ui\Admin\Action\Session\PreviewAction }

admin_session_delete:
    path: /course/{course}/session/{session}/delete
    methods: [DELETE]
    requirements:
        course: \d+
        session: \d+
    defaults: { _controller: App\Ui\Admin\Action\Session\DeleteAction }

admin_session_progression:
    path: /course/{course}/session/{session}/progression
    methods: [GET]
    requirements:
        course: \d+
        session: \d+
    defaults: { _controller: App\Ui\Admin\Action\Session\ProgressionAction }

#
# Quiz
#
admin_session_quiz:
    path: /course/{course}/session/{session}/quiz
    methods: [GET, POST]
    requirements:
        course: \d+
        session: \d+
    defaults: { _controller: App\Ui\Admin\Action\Session\Quiz\QuestionAction }

#
# Institution
#
admin_institution_list:
    path: /institution
    methods: [GET]
    defaults: { _controller: App\Ui\Admin\Action\Institution\ListAction }

admin_institution_create:
    path: /institution/create
    methods: [GET, POST]
    defaults: { _controller: App\Ui\Admin\Action\Institution\CreateAction }

admin_institution_update:
    path: /institution/update/{institution}
    methods: [GET, POST]
    requirements:
        institution: \d+
    defaults: { _controller: App\Ui\Admin\Action\Institution\UpdateAction }

admin_institution_delete:
    path: /institution/delete/{institution}
    methods: [DELETE]
    requirements:
        institution: \d+
    defaults: { _controller: App\Ui\Admin\Action\Institution\DeleteAction }
