admin_home:
    path: /
    methods: [GET]
    defaults: { _controller: App\Ui\Admin\Action\HomeAction }

admin_course_list:
    path: /course
    methods: [GET]
    defaults: { _controller: App\Ui\Admin\Action\Course\ListAction }

admin_course_create:
    path: /course/create
    methods: [GET, POST]
    defaults: { _controller: App\Ui\Admin\Action\Course\CreateAction }
